{
  config,
  pkgs,
  lib,
  ...
}:

let
  # Remember to update firmware.nix and copy the updated DTB to /boot when bumping the kernel version (if updated)
  modDirVersion = "6.18.39";
  tag = "stable_20260724";

  linux_rpi5 =
    (pkgs.buildLinux {
      version = "${modDirVersion}-${tag}";
      inherit modDirVersion;

      src = pkgs.fetchFromGitHub {
        owner = "raspberrypi";
        repo = "linux";
        rev = tag;
        hash = "sha256-IT/SkF458oLmnFIPbN76Qp6s8KVxKQOC02XmN7NRdBc=";
      };

      defconfig = "bcm2712_defconfig";

      kernelPatches = [
        pkgs.kernelPatches.bridge_stp_helper
        pkgs.kernelPatches.request_key_helper
      ];

      features = {
        efiBootStub = false;
        #iwlwifi = false;
      };

      ignoreConfigErrors = true;

      extraMeta = {
        platforms = [ "aarch64-linux" ];
        hydraPlatforms = [ "aarch64-linux" ];
      };
    }).overrideAttrs
      (oldAttrs: {
        postConfigure = ''
          sed -i $buildRoot/.config -e 's/^CONFIG_LOCALVERSION=.*/CONFIG_LOCALVERSION=""/'
          sed -i $buildRoot/.config -e 's/^CONFIG_LOCALVERSION_AUTO=.*/CONFIG_LOCALVERSION_AUTO=n/'
          sed -i $buildRoot/include/config/auto.conf -e 's/^CONFIG_LOCALVERSION=.*/CONFIG_LOCALVERSION=""/'

          # Force-disable (any value -> '# CONFIG_X is not set')
          sed -i $buildRoot/.config -E \
            -e 's/^CONFIG_(DRM_NOUVEAU|DRM_AMDGPU|DRM_RADEON|DRM_I915|DRM_VGEM|DRM_VKMS|DRM_BOCHS|DRM_CIRRUS_QEMU|HYPERV|HYPERV_BALLOON|HYPERV_NET|HYPERV_KEYBOARD|FB_HYPERV|DRM_HYPERV|HYPERV_STORAGE|VMWARE_BALLOON|VMWARE_VMCI|VMWARE_PVSCSI|DRM_VMWGFX|DRM_VBOXVIDEO|DRM_QXL|XEN|BTRFS_FS|DEBUG_KERNEL|INPUT_JOYSTICK|INPUT_JOYDEV|INPUT_TABLET|INPUT_TOUCHSCREEN|NFC|MEDIA_TUNER|MEDIA_SUBDRV_AUTOMOUNT|SCSI_CONSTANTS|SCSI_LOGGING|SCSI_PROC_FS|SCSI_SPI_ATTRS|SCSI_FC_ATTRS|SCSI_SAS_ATTRS|SCSI_SAS_LIBSAS|SCSI_SRP_ATTRS|SCSI_MVSAS|SCSI_MVUMI|SCSI_ARCMSR|SCSI_AIC7XXX|SCSI_AIC79XX|SCSI_AACRAID|SCSI_MPT2SAS|SCSI_MPT3SAS|SCSI_SMARTPQI|SCSI_PMCRAID|SCSI_IPS|SCSI_INITIO|SCSI_INIA100|SCSI_STEX|SCSI_SYM53C8XX_2|SCSI_QLOGIC_1280|SCSI_QLOGIC_FC|SCSI_QLOGIC_IPS|SCSI_QLOGIC_QLA_ISCSI|SCSI_LPFC|SCSI_BFA_FC|SCSI_CHELSIO_FCOE|SCSI_DC395x|SCSI_AM53C974|SCSI_WD719X|SCSI_DEBUG|SCSI_OSD_INITIATOR|SCSI_OSD_ULD|SCSI_DH|SCSI_DH_RDAC|SCSI_DH_HP_SW|SCSI_DH_EMC|SCSI_DH_ALUA|SCSI_VIRTIO|JFS_FS|REISERFS_FS|XFS_FS|F2FS_FS|OCFS2_FS|GFS2_FS|UFS_FS|QNX4FS_FS|QNX6FS_FS|SYSV_FS|AFFS_FS|AFS_FS|9P_FS|CIFS|SMB_SERVER|ISO9660_FS|UDF_FS|HFS_FS|HFSPLUS_FS|NTFS_RW|NCP_FS|NCPFS_FS|BLK_DEV_RAM|BLK_DEV_NBD|BLK_DEV_RBD|BLK_DEV_MD|MD_LINEAR|MD_RAID0|MD_RAID1|MD_RAID10|MD_RAID456|MD_MULTIPATH|BLK_DEV_DRBD|BLK_DEV_PMEM|CDROM|BLK_DEV_SR|BLK_DEV_SCD|BLK_DEV_UBLK|ATA|SATA_AHCI_PLATFORM|ATA_PIIX|ATA_GENERIC|SATA_AHCI|PATA_ACPI|PATA_ALI|PATA_AMD|PATA_ARTOP|PATA_ATIIXP|PATA_ATP867X|PATA_CMD64X|PATA_CS5520|PATA_CS5530|PATA_CS5535|PATA_CS5536|PATA_CYPRESS|PATA_EFAR|PATA_HPT366|PATA_HPT37X|PATA_HPT3X2N|PATA_HPT3X3|PATA_IT8213|PATA_IT821X|PATA_JMICRON|PATA_MARVELL|PATA_MPIIX|PATA_OLDPIIX|PATA_OPTIDMA|PATA_PDC2027X|PATA_PDC_OLD|PATA_RADISYS|PATA_RDC|PATA_SCH|PATA_SERVERWORKS|PATA_SIL680|PATA_SIS|PATA_TOSHIBA|PATA_TRIFLEX|PATA_VIA|PATA_WINBOND|IP_VS|IP_VS_PROTO_TCP|IP_VS_PROTO_UDP|IP_VS_PROTO_ESP|IP_VS_PROTO_AH|IP_VS_PROTO_SCTP|IP_VS_RR|IP_VS_WRR|IP_VS_WLC|IP_VS_LBLC|IP_VS_LBLCR|IP_VS_DH|IP_VS_SH|IP_VS_SED|IP_VS_NQ|IP_VS_TAB_BITS|IP_VS_MH|IP_VS_MH_TAB_INDEX|IP_VS_FTP|IP_VS_PE_SIP|IP_VS_NFCT|IP_VS_SH_TAB_BITS|IP_VS_TAB_SIZE|IP_VS_TCP_CHECKSUM|IP_VS_IPV6|IP_VS_DEBUG|XFRM|XFRM_OFFLOAD|XFRM_ALGO|XFRM_USER|XFRM_INTERFACE|XFRM_SUB_POLICY|XFRM_STATISTICS|INET_XFRM_MODE_TRANSPORT|INET_XFRM_MODE_TUNNEL|INET_XFRM_MODE_BEET|INET_XFRM_MODE_ROUTEOPTIMIZATION|INET_AH|INET_ESP|INET_ESP_OFFLOAD|INET_IPCOMP|INET6_ESP|INET6_ESP_OFFLOAD|INET6_AH|INET6_IPCOMP|INET6_XFRM_TUNNEL|INET6_TUNNEL|IPV6_MIP6|IPV6_ILA|IPV6_VTI|IPV6_SIT|IPV6_SIT_6RD|IPV6_TUNNEL|IPV6_GRE|IPV6_FOU|IPV6_FOU_TUNNEL|NET_UDP_TUNNEL|NET_IPVTI|AF_KEY|FTRACE|FUNCTION_TRACER|FUNCTION_GRAPH_TRACER|GRAPH_TRACER|STACK_TRACER|IRQSOFF_TRACER|PREEMPT_TRACER|SCHED_TRACER|ENABLE_DEFAULT_TRACERS|DYNAMIC_FTRACE|DYNAMIC_FTRACE_WITH_REGS|DYNAMIC_FTRACE_WITH_DIRECT_CALLS|DYNAMIC_FTRACE_WITH_CALL_OPS|FTRACE_MCOUNT_USE_PATCHABLE_FUNCTION_ENTRY|FTRACE_MCOUNT_USE_CC|MCOUNT_SELECTIVE|TRACEPOINT_BENCHMARK|HAVE_FTRACE_MCOUNT_RECORD|HAVE_FUNCTION_GRAPH_TRACER|HAVE_FUNCTION_GRAPH_RET_ADDR_HOLDER|HAVE_FUNCTION_TRACER|HAVE_C_RECORDMCOUNT|HAVE_DYNAMIC_FTRACE|HAVE_DYNAMIC_FTRACE_WITH_REGS|HAVE_DYNAMIC_FTRACE_WITH_CALL_OPS|TRACE_CLOCK|KPROBES|KPROBES_ON_FTRACE|UPROBES|UPROBE_EVENTS|KPROBE_EVENTS|KPROBE_EVENTS_ON_NOTRACE|TRACER_MAX_TRACE|PROFILING|KALLSYMS|KALLSYMS_ALL|DEBUG_INFO|DEBUG_INFO_DWARF5|DEBUG_INFO_BTF|DEBUG_INFO_REDUCED|DEBUG_INFO_COMPRESSED|DEBUG_INFO_SPLIT|DEBUG_INFO_AOP|PAHOLE_HAS_BTF_TAG|BPF_JIT_ALWAYS_ON|BPF_JIT_DEFAULT_ON|FTRACE_MCOUNT_RECORD|FTRACE_SUPPORT|TRACING)=.*/# CONFIG_\1 is not set/'
        '';

        postFixup = ''
          dtbDir=$out/dtbs/broadcom
          rm -f $dtbDir/bcm283*.dtb
          copyDTB() {
            if [ -f "$dtbDir/$1" ]; then
              cp -v "$dtbDir/$1" "$dtbDir/$2"
            fi
          }
          copyDTB bcm2710-rpi-zero-2.dtb bcm2837-rpi-zero-2.dtb
          copyDTB bcm2710-rpi-3-b.dtb bcm2837-rpi-3-b.dtb
          copyDTB bcm2710-rpi-3-b-plus.dtb bcm2837-rpi-3-a-plus.dtb
          copyDTB bcm2710-rpi-3-b-plus.dtb bcm2837-rpi-3-b-plus.dtb
          copyDTB bcm2710-rpi-cm3.dtb bcm2837-rpi-cm3.dtb
          copyDTB bcm2711-rpi-4-b.dtb bcm2838-rpi-4-b.dtb
        '';
      });

in
{
  boot.kernelPackages = pkgs.linuxPackagesFor linux_rpi5;
}
